"""GENERATED by build_mg.py from wp4_period_prior_mountgunson.ipynb; do not edit by hand.

Import with this folder (or SVOI_OD) as the working directory and svoi_core importable: it defines BRANCH_MG, realize_mg, synthetic_mg.
"""
# ======== setup and Annex B rows (from the notebook) ========
import sys, io, contextlib, re, json, time, hashlib, datetime
from pathlib import Path
import numpy as np
import pandas as pd
from scipy import ndimage

sys.path.insert(0, "09_sherlock")
with contextlib.redirect_stdout(io.StringIO()):
    import svoi_core as C
PM = Path("."); assert (PM / "01_citation_table").is_dir(), "run from the SVOI_OD folder"
OUT = Path("08_prior_models/mountgunson"); FIG = OUT / "figures"; FIG.mkdir(parents=True, exist_ok=True)
CC = pd.read_csv(PM / "01_citation_table/wp4_annexC_citation_table_draft.csv").set_index("row_id")
DOSS = pd.read_csv(PM / "03_sampler_inputs/mount_gunson_t0_dossier.csv")

def cited_c(row, *numbers):
    """every number the code uses for an Annex C row must be written in that row; the status is reported, not asserted"""
    txt = CC.loc[row, "proposed_distribution"].replace(",", "")
    written = {float(x) for x in re.findall(r"\d+\.?\d*", txt)}
    for v in numbers:
        assert float(v) in written, (row, v, txt)
    return CC.loc[row, "status"]

print(f"shared core: grid {C.NX} x {C.NY} km; {len(C.G_OBS)} gravity stations, {len(C.M_OBS):,} magnetic readings; Annex A rows {len(C.CT)}")
print(f"Annex C rows: {len(CC)}; dossier statements: {len(DOSS)} (pre-t0: {(DOSS.status_t0 == 'before').sum()})"); print(CC[["parameter", "status"]].to_string())


# ======== the branch (from the notebook) ========
U, LU = C.U, C.LU
for row, nums in [("C3-1", (0.15, 0.50)), ("C3-2", (30, 150, 3.2, 10, 20, 1)), ("C4-1", (1, 15)), ("C4-2", (50, 300)), ("C4-3", (0.02, 1.0, 1, 5)), ("C4-4", (1.0, 3.5))]:
    print(f"{row}: {cited_c(row, *nums)}")
FIX_MG = dict(belt_aspect=3.2, belt_az=10.0, dep_weight=1.0, dep_window_km=20.0)   # declared: Mount Gunson corridor (RB 72/00189), depression term (PMR 58/74)
A_UNUSED = [k for k in C.draw(np.random.default_rng(0)) if k[:2] in ("L3", "L4")]

def draw_mg(r):
    p = C.draw(r)
    for k in A_UNUSED: p.pop(k)
    return p

def level3_woocalla(r, p, F):
    """reduced facies at the top of the Pandurra: the Annex A anisotropic field plus a depression term of s4"""
    p["C3-1 p_reduced"] = U(r, 0.15, 0.50); p["C3-2 belt_length_km"] = LU(r, 30, 150)
    Lb = p["C3-2 belt_length_km"]
    g = C.grf(r, Lb / 3.0, Lb / 3.0 / FIX_MG["belt_aspect"], FIX_MG["belt_az"])
    s4 = F["s4"]; dep = ndimage.uniform_filter(s4, size=int(FIX_MG["dep_window_km"])) - s4      # positive where the Pandurra top is shallower than its surroundings
    dep = -dep; dep = (dep - dep.mean()) / dep.std()                                              # positive in depressions, unit variance
    f = g + FIX_MG["dep_weight"] * dep
    return dict(reduced=f >= np.quantile(f, 1 - p["C3-1 p_reduced"]), dep=dep)

def level4_copper(r, p, F):
    p["C4-1 reach_km"] = LU(r, 1, 15); p["C4-2 body_intensity_per_1e4km2"] = LU(r, 50, 300)
    red = F["reduced"]
    if red.any() and (~red).any():
        dist_edge = ndimage.distance_transform_edt(red) * C.DX / 1e3                              # km inside the facies from its edge
        zone = red & (dist_edge <= p["C4-1 reach_km"])
    else:
        zone = red.copy()
    zone_km2 = zone.sum() * (C.DX / 1e3) ** 2
    n = r.poisson(p["C4-2 body_intensity_per_1e4km2"] * zone_km2 / 1e4) if zone.any() else 0
    ox, oy = C.weighted_points(r, n, np.ones((C.NY, C.NX)), zone)
    ores = []; host = p["L5-2 rho_pandurra"]
    for x, y in zip(ox, oy):
        A = LU(r, 0.02, 1.0); th = LU(r, 1, 5); G = U(r, 1.0, 3.5)
        iy_, ix_ = np.argmin(abs(C.YC - y)), np.argmin(abs(C.XC - x))
        vf = G / 100 / C.FIX["cu_in_ccp"] * host / C.FIX["rho_ccp"]; drho = vf * (C.FIX["rho_ccp"] - host)
        ores.append(dict(x=x, y=y, iy=int(iy_), ix=int(ix_), area_km2=A, thick_m=th, grade=G, drho=drho, depth_m=float(F["s4"][iy_, ix_]),
                         Mt=A * th * (host + drho), dist_edge_km=float(dist_edge[iy_, ix_]) if red.any() and (~red).any() else np.nan))
    return dict(zone=zone, ores=ores)

def mg_summary(p, F):
    O = F["ores"]
    return {"L5-4 basement_sd": F["basement_sd"], "L5-4 basement_logk_sd": F["basement_logk_sd"],
            **dict(n_basalt=len(F["objs"]), basalt_frac=F["basalt"].mean(), n_iron=len(F["irons"]), reduced_frac=F["reduced"].mean(),
                   zone_km2=F["zone"].sum() * (C.DX / 1e3) ** 2, n_ore=len(O), Mt_total=sum(o["Mt"] for o in O), Mt_max=max([o["Mt"] for o in O], default=0.0),
                   ore_depth_median=float(np.median([o["depth_m"] for o in O])) if O else np.nan, basement_sd_realized=F["rho_base"].std())}

BRANCH_MG = dict(name="Mount Gunson-type stratiform Cu, Annex C", citation_table="01_citation_table/wp4_annexC_citation_table_draft.csv",
                 geometry_family="flat-lying cover stack; barren piles and iron bodies; Woocalla reduced facies at the top of the Pandurra in depressions",
                 mineralization_rule="tabular Cu bodies on the post-Pandurra surface inside the reduced facies within reach of its edge; no igneous source",
                 draw=draw_mg, stages=[C.level1_frame, C.level2_basalt, level3_woocalla, level4_copper, C.level2_iron, C.level5_basement],
                 properties=C.level5_properties, summary=mg_summary)

def realize_mg(seed, keep_volume=False):
    return C.realize_branch(BRANCH_MG, seed, keep_volume)

def synthetic_mg(seed, rng_noise=True):
    out, maps, objs, ores = realize_mg(seed, keep_volume=True)
    g, t = C.forward(maps["rho"], maps["k"])
    r = np.random.default_rng(seed + 10_000_000)
    gs = C.sample(g, C.GXo, C.GYo) + (r.normal(0, C.G_SD) if rng_noise else 0)
    ms = C.sample(t, C.MXo, C.MYo) + (r.normal(0, C.RULE["mag_noise_nt"], len(C.MXo)) if rng_noise else 0)
    return out, maps, g, t, gs, ms

o43, m43, b43, e43 = realize_mg(43)
oA, mA, bA, _ = C.realize(43)
print("branch:", BRANCH_MG["name"]); print("  stages:", [f.__name__ for f in BRANCH_MG["stages"]], "+", BRANCH_MG["properties"].__name__)
print(f"seed 43: Level 1 identical to the other branches: {np.array_equal(m43['base'], mA['base'])}; piles identical: {len(b43) == len(bA) and np.allclose(b43[['x', 'y', 'length_km']].values, bA[['x', 'y', 'length_km']].values)}")
print(f"seed 43: reduced facies {o43['reduced_frac']*100:.0f}% of the window, zone {o43['zone_km2']:.0f} km2, {o43['n_ore']} Cu bodies, {o43['Mt_total']:.1f} Mt, median depth {o43['ore_depth_median']:.0f} m")

