"""Build svoi_fe.py from wp4_period_prior_middleback.ipynb, so the Sherlock run uses exactly the notebook's branch.

Run from this folder after any change to the branch cell of the notebook:  python build_fe.py
svoi_core.py (the shared setting) is copied from ../09_sherlock; rebuild it there first if the basalt notebook changed.
"""
import json
from pathlib import Path

NB = Path(__file__).resolve().parent.parent / "wp4_period_prior_middleback.ipynb"
cells = ["".join(c["source"]) for c in json.load(open(NB, encoding="utf-8"))["cells"] if c["cell_type"] == "code"]

def one(marker):
    hit = [s for s in cells if s.startswith(marker)]
    assert len(hit) == 1, (marker, len(hit))
    return hit[0]

setup = one("import sys, io, contextlib, re, json, time, hashlib, datetime")
branch = one("# ---- the Annex B draws, tied to their rows")
head = '''"""GENERATED by build_fe.py from wp4_period_prior_middleback.ipynb; do not edit by hand.

Import with this folder (or SVOI_OD) as the working directory and svoi_core importable: it defines BRANCH_FE, realize_fe, synthetic_fe.
"""
'''
body = "# ======== setup and Annex B rows (from the notebook) ========\n" + setup + "\n\n# ======== the branch (from the notebook) ========\n" + branch
out = Path(__file__).resolve().parent / "svoi_fe.py"
out.write_text(head + body + "\n", encoding="utf-8")
print(f"wrote {out.name} from {NB.name} ({len(body.splitlines())} lines)")
