"""GENERATED by build_fe.py from wp4_period_prior_middleback.ipynb; do not edit by hand.

Import with this folder (or SVOI_OD) as the working directory and svoi_core importable: it defines BRANCH_FE, realize_fe, synthetic_fe.
"""
# ======== setup and Annex B rows (from the notebook) ========
import sys, io, contextlib, re, json, time, hashlib, datetime
from pathlib import Path
import numpy as np
import pandas as pd
from scipy import ndimage

sys.path.insert(0, "09_sherlock")
with contextlib.redirect_stdout(io.StringIO()):
    import svoi_core as C                                 # the shared setting: grid, rule, operator, surveys, Level 1, barren piles, Level 5
PM = Path("."); assert (PM / "01_citation_table").is_dir(), "run from the SVOI_OD folder"
OUT = Path("08_prior_models/middleback"); FIG = OUT / "figures"; FIG.mkdir(parents=True, exist_ok=True)
CB = pd.read_csv(PM / "01_citation_table/wp4_annexB_citation_table_draft.csv").set_index("row_id")

def cited_b(row, *numbers):
    """every number the code uses for an Annex B row must be written in that row; the status is reported, not asserted"""
    txt = CB.loc[row, "proposed_distribution"].replace(",", "")
    written = {float(x) for x in re.findall(r"\d+\.?\d*", txt)}
    for v in numbers:
        assert float(v) in written, (row, v, txt)
    return CB.loc[row, "status"]

print(f"shared core: grid {C.NX} x {C.NY} km, {len(C.ZC)} layers; {len(C.G_OBS)} gravity stations, {len(C.M_OBS):,} magnetic readings; "
      f"rule {C.RULE['T_grav_mgal']:g} mGal / {C.RULE['T_mag_nt']:g} nT; Annex A rows {len(C.CT)}, all confirmed: {bool(C.CT.confirmed.str.contains('confirmed').all())}")
print(f"Annex B rows: {len(CB)}"); print(CB[["parameter", "status"]].to_string())


# ======== the branch (from the notebook) ========
# ---- the Annex B draws, tied to their rows --------------------------------------------------------------------------------
U, LU = C.U, C.LU
for row, nums in [("B2-1", (100, 500)), ("B2-2", (1, 10, 0.1, 2, 200, 2000)), ("B2-4", (0.3, 0.7)), ("B2-3", (3.0, 3.6, 5000, 50000)),
                  ("B3-1", (0.01, 0.10)), ("B3-2", (20, 60, 10)), ("B4-1", (0.1, 0.3, 0.03, 0.45, 30, 150)), ("B4-2", (60, 68, 4.3, 0.0375, 4.6, 50, 2000))]:
    print(f"{row}: {cited_b(row, *nums)}")
FIX_FE = dict(belt_aspect=10.0, belt_az=0.0, lens_az=0.0)      # declared: Middleback Range, 60 x 6 km, north-south (RB 33/00090)
LITH_FE = {**C.LITH, 9: "banded iron formation", 10: "hematite ore"}
A_UNUSED = [k for k in C.draw(np.random.default_rng(0)) if k[:2] in ("L3", "L4")]   # Annex A rows the Middleback branch does not use

def draw_fe(r):
    """the shared Annex A rows, in the same stream order as the sediment-hosted branch; the Annex B rows are drawn inside their
    stages, after Level 1 and the piles have consumed the stream, so for a given seed those two are identical in both branches"""
    p = C.draw(r)
    for k in A_UNUSED: p.pop(k)                                   # drawn to keep the stream aligned, not used by this branch
    return p

def level3_belt(r, p, F):
    p["B3-1 p_belt"] = U(r, 0.01, 0.10); p["B3-2 belt_length_km"] = LU(r, 20, 60)
    Lb = p["B3-2 belt_length_km"]
    f = C.grf(r, Lb / 3.0, Lb / 3.0 / FIX_FE["belt_aspect"], FIX_FE["belt_az"])
    return dict(belt=f >= np.quantile(f, 1 - p["B3-1 p_belt"]))

def level2_lenses(r, p, F):
    p["B2-1 lens_intensity_per_1e4km2_belt"] = LU(r, 100, 500); p["B2-3 rho_bif"] = U(r, 3.0, 3.6); p["B2-3 k_bif"] = LU(r, 5000, 50000)
    p["B2-4 bif_fraction"] = U(r, 0.3, 0.7)
    belt = F["belt"]; belt_km2 = belt.sum() * (C.DX / 1e3) ** 2
    n = r.poisson(p["B2-1 lens_intensity_per_1e4km2_belt"] * belt_km2 / 1e4) if belt.any() else 0
    lx, ly = C.weighted_points(r, n, np.ones((C.NY, C.NX)), belt)
    lid = np.zeros((C.NY, C.NX), int); lenses = []
    for j, (x, y) in enumerate(zip(lx, ly), 1):
        L = LU(r, 1, 10); w = LU(r, 0.1, 2.0); E = LU(r, 200, 2000)
        m = C.ellipse(x, y, L, L / w, FIX_FE["lens_az"])
        if not m.any(): m[np.argmin(abs(C.YC - y)), np.argmin(abs(C.XC - x))] = True
        area = np.pi * L * w / 4; fill = min(1.0, area / (m.sum() * (C.DX / 1e3) ** 2))
        lid[m & (lid == 0)] = j
        iy, ix = np.argmin(abs(C.YC - y)), np.argmin(abs(C.XC - x))
        lenses.append(dict(obj=j, x=x, y=y, length_km=L, width_km=w, depth_extent_m=E, fill=fill, fill_bif=fill * p["B2-4 bif_fraction"], area_km2=area, depth_m=float(F["base"][iy, ix])))
    return dict(lid=lid, lenses=lenses, irons=[], iid=np.zeros((C.NY, C.NX), int))    # irons empty: the Annex A iron slab is replaced by the lenses

def level4_enrich(r, p, F):
    p["B4-1 ore_bodies_per_km"] = U(r, 0.1, 0.3)
    enr = np.zeros((C.NY, C.NX), int); ores = []
    for o in F["lenses"]:
        cells_ = np.argwhere(F["lid"] == o["obj"])
        if len(cells_) == 0: continue
        n_b = r.poisson(p["B4-1 ore_bodies_per_km"] * o["length_km"])
        for _ in range(n_b):
            iy_, ix_ = cells_[r.integers(0, len(cells_))]                          # a random cell of the range
            area = LU(r, 0.03, 0.45); th = min(LU(r, 30, 150), o["depth_extent_m"])     # plan area (km2) and enrichment depth (m)
            G = U(r, 60, 68); rho = 4.3 + 0.0375 * (G - 60); kk = LU(r, 50, 2000)
            enr[iy_, ix_] = o["obj"]
            ores.append(dict(lens=o["obj"], x=float(C.XC[ix_]), y=float(C.YC[iy_]), iy=int(iy_), ix=int(ix_), grade=G, rho=rho, k=kk,
                             depth_m=float(F["base"][iy_, ix_]), thick_m=th, area_km2=area, fill=area / (C.DX / 1e3) ** 2, Mt=area * th * rho))   # km2 x m x t/m3 = Mt
    return dict(enr=enr, ores=ores)

def fe_properties(p, F):
    V = C.level5_properties(p, F)                                          # cover, barren piles, basement fields (shared)
    lith, rho3, k3, res3 = V["lith"], V["rho"], V["k"], V["res"]
    z = C.ZC[None, None, :]; base3 = F["base"][:, :, None]
    for o in F["lenses"]:                                                  # the range: BIF for a fraction of its volume, as a contrast scaled by fill x BIF fraction
        m3 = (F["lid"][:, :, None] == o["obj"]) & (lith == 7) & (z >= base3) & (z < base3 + o["depth_extent_m"])
        lith[m3] = 9
        rho3[m3] = rho3[m3] + o["fill_bif"] * (p["B2-3 rho_bif"] - rho3[m3]); k3[m3] = k3[m3] + o["fill_bif"] * (p["B2-3 k_bif"] - k3[m3])
    for o in F["ores"]:                                                    # each ore body replaces the rock of its cell over its plan area, from the unconformity down its depth
        zc = C.ZC; b0 = F["base"][o["iy"], o["ix"]]; kz = (zc >= b0) & (zc < b0 + o["thick_m"])
        lith[o["iy"], o["ix"], kz] = 10
        rho3[o["iy"], o["ix"], kz] += o["fill"] * (o["rho"] - rho3[o["iy"], o["ix"], kz]); k3[o["iy"], o["ix"], kz] += o["fill"] * (o["k"] - k3[o["iy"], o["ix"], kz])
    return dict(lith=lith, rho=rho3, k=k3, res=res3)

def fe_summary(p, F):
    L, O = F["lenses"], F["ores"]
    return {"L5-4 basement_sd": F["basement_sd"], "L5-4 basement_logk_sd": F["basement_logk_sd"],
            **dict(n_basalt=len(F["objs"]), basalt_frac=F["basalt"].mean(), belt_frac=F["belt"].mean(), belt_km2=F["belt"].sum() * (C.DX / 1e3) ** 2,
                   n_lens=len(L), lens_km2=sum(o["area_km2"] for o in L), n_ore=len(O), Fe_Mt_total=sum(o["Mt"] for o in O),
                   Fe_Mt_max=max([o["Mt"] for o in O], default=0.0), basement_sd_realized=F["rho_base"].std())}

BRANCH_FE = dict(name="Middleback-type iron body, Annex B", citation_table="01_citation_table/wp4_annexB_citation_table_draft.csv",
                 geometry_family="steep BIF ranges (BIF interfingered with schist) in belts of the basement, below the unconformity; barren basalt flows on it",
                 mineralization_rule="hematite ore bodies, a Poisson number per km of range, each of Middleback plan area, from the unconformity down; no copper",
                 draw=draw_fe, stages=[C.level1_frame, C.level2_basalt, level3_belt, level2_lenses, level4_enrich, C.level5_basement],
                 properties=fe_properties, summary=fe_summary)

def realize_fe(seed, keep_volume=False):
    return C.realize_branch(BRANCH_FE, seed, keep_volume)

def synthetic_fe(seed, rng_noise=True):
    out, maps, objs, ores = realize_fe(seed, keep_volume=True)
    g, t = C.forward(maps["rho"], maps["k"])
    r = np.random.default_rng(seed + 10_000_000)
    gs = C.sample(g, C.GXo, C.GYo) + (r.normal(0, C.G_SD) if rng_noise else 0)
    ms = C.sample(t, C.MXo, C.MYo) + (r.normal(0, C.RULE["mag_noise_nt"], len(C.MXo)) if rng_noise else 0)
    return out, maps, g, t, gs, ms

o43, m43, b43, e43 = realize_fe(43)
oA, mA, bA, _ = C.realize(43)
print("branch:", BRANCH_FE["name"]); print("  stages:", [f.__name__ for f in BRANCH_FE["stages"]], "+", BRANCH_FE["properties"].__name__)
print(f"seed 43: Level 1 identical to the sediment-hosted branch: {np.array_equal(m43['base'], mA['base'])}; piles identical: {len(b43) == len(bA) and np.allclose(b43[['x', 'y', 'length_km']].values, bA[['x', 'y', 'length_km']].values)}")
print(f"seed 43: belt {o43['belt_frac']*100:.1f}% of the window ({o43['belt_km2']:.0f} km2), {o43['n_lens']} ranges, {o43['n_ore']} ore bodies, {o43['Fe_Mt_total']:.0f} Mt Fe ore")

