"""GENERATED by build_core.py from wp4_period_prior_sediment_hosted.ipynb; do not edit by hand.

Import with the SVOI_OD folder as the working directory (paths are relative to it).
"""
# ======== data and citation table (from the notebook) ========
from pathlib import Path
import re
import numpy as np
import pandas as pd
from scipy import ndimage, stats
from pyproj import Transformer
import discretize

PM = Path(".")                                               # this notebook sits in the SVOI_OD folder
FIG = Path("08_prior_models/figures")
TAB = Path("08_prior_models")
assert (PM / "01_citation_table").is_dir(), "run from the SVOI_OD folder"
FIG.mkdir(parents=True, exist_ok=True)

CT = pd.read_csv(PM / "01_citation_table/wp4_annexA_citation_table_draft.csv").set_index("row_id")
TG = pd.read_csv(PM / "03_sampler_inputs/wp4_prior_lineament_targets_1974.csv")
WIN = pd.read_csv(PM / "03_sampler_inputs/study_windows.csv").set_index("window").loc["regional"]
ANNEX_GREY = "#e3e3e3"                                  # shading for a confirmed or stated range
OD_LON, OD_LAT = 136.887, -30.441                      # Olympic Dam, for orientation only; never used by the sampler

def cited(row, *numbers):
    """assert that every number the code uses for a row is written in that row's confirmed distribution"""
    txt = CT.loc[row, "proposed_distribution"].replace(",", "")
    written = {float(x) for x in re.findall(r"\d+\.?\d*", txt)}
    for v in numbers:
        assert float(v) in written, (row, v, txt)
    assert str(CT.loc[row, "confirmed"]).startswith("confirmed") or "confirmed" in str(CT.loc[row, "confirmed"]), row
    return True

print(f"citation table: {len(CT)} rows, all confirmed: {bool(CT.confirmed.str.contains('confirmed').all())}")
print(CT[["parameter", "status"]].to_string())
TG["in_regional_window"] = TG.lon.between(WIN.lon_min, WIN.lon_max) & TG.lat.between(WIN.lat_min, WIN.lat_max)
print(f"window '{WIN.name}': lon {WIN.lon_min} to {WIN.lon_max}, lat {WIN.lat_min} to {WIN.lat_max} ({WIN.status}); {WIN.source}")
print(f"\nO'Driscoll 1974 targets: {len(TG)}, in the regional window: {int(TG.in_regional_window.sum())}")


# ======== map grid, survey geometry, rule and forward operator, Part 0 (from the notebook) ========
# ---- Part 0 setup: window map grid, survey geometry, the anomaly rule and the forward operator. No measured value is read here.
from scipy.spatial import Delaunay
from scipy.interpolate import LinearNDInterpolator, RegularGridInterpolator

# the window map grid, GDA94 / MGA zone 53, 1 km cells (Part A adds the depth axis to make the sampler mesh)
to_mga = Transformer.from_crs("EPSG:4326", "EPSG:28353", always_xy=True)
xs, ys = to_mga.transform([WIN.lon_min, WIN.lon_max, WIN.lon_min, WIN.lon_max], [WIN.lat_min, WIN.lat_min, WIN.lat_max, WIN.lat_max])
X0, X1, Y0, Y1 = np.floor(min(xs) / 1e3) * 1e3, np.ceil(max(xs) / 1e3) * 1e3, np.floor(min(ys) / 1e3) * 1e3, np.ceil(max(ys) / 1e3) * 1e3
DX = 1000.0
NX, NY = int((X1 - X0) / DX), int((Y1 - Y0) / DX)
XC = X0 + DX * (np.arange(NX) + 0.5); YC = Y0 + DX * (np.arange(NY) + 0.5)
GX, GY = np.meshgrid(XC, YC)                           # (NY, NX) map grid
AREA_KM2 = NX * NY * (DX / 1e3) ** 2
HZ = [25.0] * 80 + [25.0 * 1.5 ** k for k in range(1, 11)]          # layer thicknesses: 80 x 25 m to 2 km, then 10 padding layers to about 6.3 km
OBS = PM / "04_prior_predictive_observed"

# ---- the anomaly rule and the ambient field: fixed here, before any measured value is opened and before any realization exists
RULE = dict(T_grav_mgal=2.0,          # anomaly threshold, twice the station noise (about 1 mGal, below)
            T_mag_nt=20.0,            # anomaly threshold, four times the declared 1962 reading noise
            mag_noise_nt=5.0,         # declared white noise on the 1962 readings
            min_cells=3,              # an anomaly is at least 3 connected 1 km cells (3 km2)
            mag_decimate=4,           # every 4th reading along line (about 290 m)
            elev_gradient=0.1967)     # Bouguer elevation factor, mGal/m at 2.67 g/cm3
FIELD = dict(F_nt=57776.0, inc=-62.44, dec=6.00, clearance_m=150.0)   # April 1962 field over the window (DGRF); P234 clearance
N_ENS, SEED0 = 200, 1000
C_G, C_M = "k", "#c0504d"                                          # plot colours for the two surveys

# ---- survey geometry: where the 1969 stations and the 1962 readings are, and the declared accuracies. The values stay closed.
GRAV_FILE = OBS / "gravity_stations_pre1975_full_surveys.csv"           # the complete 1969 BMR helicopter surveys 196953 and 196955 (1,912 stations); the window selects
gv_all = pd.read_csv(GRAV_FILE, usecols=["SURVEY_NUMBER", "LONGITUDE", "LATITUDE", "ACCURACY_OF_OBSERVED_GRAVITY", "ACCURACY_OF_GEOID_GND_ELEV"])
G_IDX = np.flatnonzero(gv_all.LONGITUDE.between(WIN.lon_min, WIN.lon_max) & gv_all.LATITUDE.between(WIN.lat_min, WIN.lat_max))
gv = gv_all.iloc[G_IDX].reset_index(drop=True)
GXo, GYo = to_mga.transform(gv.LONGITUDE.values, gv.LATITUDE.values)
G_SD = np.sqrt((gv.ACCURACY_OF_OBSERVED_GRAVITY.values / 10.0) ** 2 + (RULE["elev_gradient"] * gv.ACCURACY_OF_GEOID_GND_ELEV.values) ** 2)
CACHE = OBS / "P234-line-magnetic-AWAGS_MAG_2010_cache.npz"          # built once from the netCDF, so netCDF4 is not needed afterwards
if not CACHE.exists():
    import netCDF4
    with netCDF4.Dataset(OBS / "P234-line-magnetic-AWAGS_MAG_2010.nc") as ds:
        _lon, _lat = np.asarray(ds["longitude"][:], float), np.asarray(ds["latitude"][:], float)
        _mag = np.ma.filled(ds["mag_awagsLevelled"][:].astype(float), np.nan); _line = np.asarray(ds["line_index"][:])
    np.savez_compressed(CACHE, lon=_lon, lat=_lat, mag=_mag, line=_line)
z = np.load(CACHE); lon, lat, line = z["lon"], z["lat"], z["line"]
valid = np.isfinite(z["mag"])                                          # only the validity flag of each reading is used here
w = (lon >= WIN.lon_min) & (lon <= WIN.lon_max) & (lat >= WIN.lat_min) & (lat <= WIN.lat_max) & valid
idx = np.flatnonzero(w)[::RULE["mag_decimate"]]
MXo, MYo = to_mga.transform(lon[idx], lat[idx]); M_LINE = line[idx]
M_SD = np.full(len(MXo), RULE["mag_noise_nt"])
TRI_G, TRI_M = Delaunay(np.c_[GXo, GYo]), Delaunay(np.c_[MXo, MYo])

# ---- the anomaly rule as code: remove a plane, grid to the map cells, keep connected groups above the threshold ------------
def detrend(x, y, v):
    A = np.c_[np.ones_like(x), (x - X0) / 1e3, (y - Y0) / 1e3]
    return v - A @ np.linalg.lstsq(A, v, rcond=None)[0]

def anomaly_stats(tri, x, y, v, T):
    res = detrend(x, y, v)
    grid = LinearNDInterpolator(tri, res)(GX, GY)
    ok = np.isfinite(grid)
    lab, n = ndimage.label(ok & (grid >= T), structure=np.ones((3, 3)))
    size = ndimage.sum(np.ones_like(grid), lab, np.arange(1, n + 1)); keep = size >= RULE["min_cells"]
    peak = np.asarray(ndimage.maximum(np.where(ok, grid, -np.inf), lab, np.arange(1, n + 1)))[keep]
    width = 2 * np.sqrt(size[keep] / np.pi)                              # km, cells are 1 km2
    s = dict(n_per_1e4km2=keep.sum() / ok.sum() * 1e4, amp_median=np.median(peak) if len(peak) else np.nan,
             amp_p90=np.percentile(peak, 90) if len(peak) else np.nan, width_median_km=np.median(width) if len(width) else np.nan,
             residual_sd=res.std())
    return s, grid, np.isin(lab, np.flatnonzero(keep) + 1)

# ---- the forward operator: layer-by-layer FFT (Blakely 1995, eqs 11.35 and 11.44 form), induced magnetization along FIELD ----
GCONST, MU0 = 6.674e-11, 4e-7 * np.pi
def make_forward(dx, hz, padn, ny, nx):
    # returns forward(rho, k_cgs) -> (gravity at the ground in mGal, total-field anomaly at FIELD clearance in nT) on an ny x nx grid of dx cells
    py, px = (padn - ny) // 2, (padn - nx) // 2
    kx, ky = np.meshgrid(2 * np.pi * np.fft.fftfreq(padn, dx), 2 * np.pi * np.fft.fftfreq(padn, dx))
    kk = np.hypot(kx, ky); kk[0, 0] = 1e-12
    zt = np.r_[0.0, np.cumsum(hz[:-1])]; zb = np.cumsum(hz)                # layer tops and bottoms (m), top first
    inc, dec = np.radians(FIELD["inc"]), np.radians(FIELD["dec"])
    fx, fy, fz = np.cos(inc) * np.sin(dec), np.cos(inc) * np.cos(dec), np.sin(inc)    # east, north, down
    theta2 = (fz + 1j * (fx * kx + fy * ky) / kk) ** 2                     # induced: magnetization parallel to the field
    hc = FIELD["clearance_m"]
    eg = [(np.exp(-kk * a) - np.exp(-kk * b)) / kk for a, b in zip(zt, zb)]
    em = [np.exp(-kk * (a + hc)) - np.exp(-kk * (b + hc)) for a, b in zip(zt, zb)]
    pad = lambda a: np.pad(a, ((py, padn - ny - py), (px, padn - nx - px)), mode="reflect")
    def forward(rho, k_cgs):
        g = np.zeros((padn, padn), complex); t = np.zeros((padn, padn), complex)
        M = k_cgs * 1e-6 * 4 * np.pi * FIELD["F_nt"] * 1e-9 / MU0        # cgs susceptibility to SI, induced magnetization (A/m)
        for l in range(rho.shape[2]):
            r, m = rho[:, :, l], M[:, :, l]
            if np.ptp(r) > 0: g += np.fft.fft2(pad(r - r.mean())) * eg[l]
            if np.ptp(m) > 0: t += np.fft.fft2(pad(m - m.mean())) * em[l]
        g *= 2 * np.pi * GCONST * 1000.0 * 1e5; t *= 2 * np.pi * 1e-7 * theta2 * 1e9
        g[0, 0] = t[0, 0] = 0
        crop = (slice(py, py + ny), slice(px, px + nx))
        return np.real(np.fft.ifft2(g))[crop], np.real(np.fft.ifft2(t))[crop]
    forward.layers, forward.padn = (zt, zb), padn
    return forward

print(f"map grid: origin E {X0:,.0f} m, N {Y0:,.0f} m, {NX} x {NY} cells of {DX:.0f} m, {AREA_KM2:,.0f} km2")
print(f"1969 gravity: {len(GXo)} stations, noise sd {np.median(G_SD):.2f} mGal (observed gravity {np.median(gv.ACCURACY_OF_OBSERVED_GRAVITY) / 10:.1f} mGal, elevation {np.median(gv.ACCURACY_OF_GEOID_GND_ELEV):.0f} m)")
print(f"1962 magnetics: {w.sum():,} readings on {len(np.unique(line[w]))} line segments in the window, {len(MXo):,} used; declared noise {RULE['mag_noise_nt']:.0f} nT")
print("rule:", RULE); print("field:", FIELD)

# ======== sampler, Part A (from the notebook) ========
# ---- mesh: the Part 0 map grid (1 km cells) with the depth axis, 25 m layers to 2 km then padding -----------------
MESH = discretize.TensorMesh([[DX] * NX, [DX] * NY, HZ[::-1]], origin=[X0, Y0, -sum(HZ)])
ZC = -MESH.cell_centers_z[::-1]                        # cell-centre depths below surface (m), top layer first
TX, TYY = to_mga.transform(TG.lon.values, TG.lat.values)
IN_CIRCLE = np.zeros((NY, NX), bool)
for x, y, r in zip(TX, TYY, TG.radius_km.values):
    IN_CIRCLE |= (GX - x) ** 2 + (GY - y) ** 2 <= (r * 1e3) ** 2
ODX, ODY = to_mga.transform(OD_LON, OD_LAT)

# ---- fixed settings (held constant, not sampled; README of annexA_prior_model) --------------------------------------
FIX = dict(rho_basement=2.60, k_basement=500.0, res_basalt=3100.0, res_basement=5000.0,
           basalt_aspect=4.7 / 3.6, basalt_az=157.0,          # Roopena outcrop, PORT AUGUSTA 1968
           belt_aspect=32.0 / 10.0, belt_az=10.0,              # Mount Gunson corridor, Johns 1972 (RB 72/00189)
           cu_in_ccp=0.346, rho_ccp=4.2,                       # chalcopyrite, Parasnis 1973 Table V
           iron_ratio=0.15 / 0.40, iron_aspect=3.0, iron_az=0.0, iron_thick_m=200.0, k_iron=5000.0,   # Change 1: iron-oxide bodies (Task 3 weights; Middleback reports)
           rho_b_mean=2.65, rho_b_min=2.50, rho_b_max=3.12,                                          # Change 1: basement density field
           k_b_median=1120.0, k_b_min=10.0, k_b_max=20000.0,                                          # Change 2: basement susceptibility field (L5-6); Change 4: median 1,120 (Grant and West Table 12-3, rhyolite)
           domain_km=30.0, texture_km=6.0, domain_share=0.8)                                          # Change 5: two-scale basement fields (both), share of variance at the domain scale; Change 8 (2026-10-02): texture 4 -> 6 km, the smallest setting that passes the magnetic count and width on the Andamooka sheet (08_prior_models/sensitivity/)
LITH = {1: "Andamooka Limestone", 2: "Arcoona Quartzite", 3: "unnamed siltstones", 4: "Woomera Shale",
        5: "Pandurra Formation", 6: "basalt", 7: "basement", 8: "iron-oxide body"}

# ---- the draws, each tied to its citation row -------------------------------------------------------------------------
cited("L1-1", 320, 670, 0.46, 0.54, 0.075, 0.24, 0.23, 0.53)                               # Change 6 (2026-09-23): one draw, total cover to basement
cited("L1-2", 20, 10, 50); cited("L1-3", 0, 150); cited("L2-1", 2, 10); cited("L2-2", 2, 20, 75, 300)
cited("L2-3", 1, 18); cited("L3-1", 0.05, 0.30); cited("L3-2", 30, 150, 0.5, 5); cited("L4-1", 0, 15)
cited("L4-2", 0.09, 0.35); cited("L4-3", 1, 5); cited("L4-4", 1, 15, 1.0, 4.5)
cited("L5-1", 2.80, 0.12, 2.60, 3.35, 20, 26000); cited("L5-2", 2.60, 2.70, 2.10, 2.20, 2.44, 0.05, 10, 100, 1, 1000)
cited("L2-4", 0.3, 3, 3.0, 4.5); cited("L5-4", 0.03, 0.10, 0.5, 1.0)                        # Change 1 and 2 rows (2026-09-23), bundled in Change 6: iron-body size; density, basement density; susceptibility variation
U = lambda r, a, b: r.uniform(a, b)
LU = lambda r, a, b: float(np.exp(r.uniform(np.log(a), np.log(b))))

def draw(r):
    """one set of realization-level parameters; row ids in the keys"""
    return {"L1-1 cover_total_m": U(r, 320, 670),                       # Change 6: total cover to basement, one draw; units are fixed fractions of it
            "L1-2 corr_length_km": LU(r, 10, 50), "L1-3 relief_m": U(r, 0, 150),
            "L2-1 intensity_per_1e4km2": U(r, 2, 10), "L2-3 basalt_multiplier": U(r, 1, 18),
            "L3-1 p_reduced": U(r, 0.05, 0.30), "L3-2 belt_length_km": LU(r, 30, 150),
            "L4-1 reach_d_km": U(r, 0, 15), "L4-2 p_ore": U(r, 0.09, 0.35), "L4-3 ore_multiplier": U(r, 1, 5),
            "L5-2 rho_quartzite": U(r, 2.60, 2.70), "L5-2 rho_shale": U(r, 2.10, 2.60), "L5-2 rho_limestone": U(r, 2.20, 2.70),
            "L5-2 rho_pandurra": r.normal(2.44, 0.05), "L5-2 k_cover": LU(r, 10, 100), "L5-2 res_cover": LU(r, 1, 1000)}

def grf(r, lx_km, ly_km=None, az=0.0, pad=2):
    """zero-mean unit-variance Gaussian random field on the map grid; correlation lengths along az and across it"""
    ly_km = lx_km if ly_km is None else ly_km
    ny, nx = NY * pad, NX * pad
    kx = np.fft.fftfreq(nx, d=DX / 1e3) * 2 * np.pi; ky = np.fft.fftfreq(ny, d=DX / 1e3) * 2 * np.pi
    KX, KY = np.meshgrid(kx, ky); a = np.radians(az)
    kpar = KX * np.sin(a) + KY * np.cos(a); kper = KX * np.cos(a) - KY * np.sin(a)
    amp = np.exp(-((kpar * lx_km) ** 2 + (kper * ly_km) ** 2) / 8.0)
    f = np.real(np.fft.ifft2(np.fft.fft2(r.standard_normal((ny, nx))) * amp))[:NY, :NX]
    return (f - f.mean()) / f.std()

def ellipse(x0, y0, length_km, aspect, az):
    a = np.radians(az); dx, dy = (GX - x0) / 1e3, (GY - y0) / 1e3
    u = dx * np.sin(a) + dy * np.cos(a); v = dx * np.cos(a) - dy * np.sin(a)
    return (u / (length_km / 2)) ** 2 + (v / (length_km / 2 / aspect)) ** 2 <= 1.0

def weighted_points(r, n, weight, mask=None):
    """n random map points with probability proportional to weight (optionally inside mask); jittered inside cells"""
    w = weight.astype(float) * (1 if mask is None else mask)
    if n == 0 or w.sum() == 0: return np.empty(0), np.empty(0)
    idx = r.choice(w.size, size=n, p=(w / w.sum()).ravel())
    iy, ix = np.unravel_index(idx, w.shape)
    return XC[ix] + r.uniform(-DX / 2, DX / 2, n), YC[iy] + r.uniform(-DX / 2, DX / 2, n)

# ---- the five levels as stages; a branch is data that names its draw, stages, properties and summary (annex Section 7, Step 17) ----
def level1_frame(r, p, F):
    T0, lc = p["L1-1 cover_total_m"], p["L1-2 corr_length_km"]
    g = np.radians(r.uniform(0, 360))
    trend = ((GX - GX.mean()) * np.sin(g) + (GY - GY.mean()) * np.cos(g)) / (NX * DX / 2)
    total = np.clip(T0 * (1 + 0.20 * grf(r, lc) + 0.20 * trend), 50, None)          # total cover to basement (L1-1), one draw
    cover = total * 0.46                                                            # Stuart Shelf succession 0.46, Pandurra 0.54 (fixed shares, row L1-1)
    fl = 0.075                                                                      # Andamooka Limestone share of the succession (fixed, row L1-1)
    s1 = cover * fl; s2 = s1 + cover * (1 - fl) * 0.24; s3 = s2 + cover * (1 - fl) * 0.23; s4 = cover
    rel = grf(r, lc); rel = p["L1-3 relief_m"] * ((rel - rel.min()) / (rel.max() - rel.min()) - 0.5)
    base = total + rel                                                              # top of basement between the targets
    base = np.where(IN_CIRCLE, np.maximum(base - p["L1-3 relief_m"], s4 + 25.0), base)   # Change 9 (2026-10-06): a horst under each O'Driscoll target, raised by the L1-3 relief draw A (0 to 150 m, the Pernatty Grit high of Bulletin 41 p. 29) and never above the base of the Pandurra; cover undisturbed; no new draw
    return dict(cover=cover, s1=s1, s2=s2, s3=s3, s4=s4, base=base)

def level2_basalt(r, p, F):
    lam, M2, fin = p["L2-1 intensity_per_1e4km2"], p["L2-3 basalt_multiplier"], IN_CIRCLE.mean()
    n_obj = r.poisson(lam * AREA_KM2 / 1e4)
    bx, by = weighted_points(r, n_obj, np.where(IN_CIRCLE, M2, 1.0) / (fin * M2 + (1 - fin)))
    btop = np.full((NY, NX), np.nan); bid = np.zeros((NY, NX), int); objs = []
    for j, (x, y) in enumerate(zip(bx, by), 1):
        L = LU(r, 2, 20); t = LU(r, 75, 300)
        rho = stats.truncnorm.rvs((2.60 - 2.80) / 0.12, (3.35 - 2.80) / 0.12, loc=2.80, scale=0.12, random_state=r)
        k = LU(r, 20, 26000)                                              # L5-1, corrected 2026-09-23 (Parasnis Table I is in rationalised units)
        m = ellipse(x, y, L, FIX["basalt_aspect"], FIX["basalt_az"])
        btop = np.where(m, np.maximum(F["base"] - t, F["s4"]), btop); bid[m] = j
        objs.append(dict(obj=j, x=x, y=y, length_km=L, thickness_m=t, rho=rho, k=k,
                         in_circle=bool(IN_CIRCLE[np.argmin(abs(YC - y)), np.argmin(abs(XC - x))])))
    basalt = bid > 0
    return dict(btop=btop, bid=bid, basalt=basalt, objs=objs, contact=np.where(basalt, btop, F["base"]))

def level3_redox(r, p, F):
    Lb = p["L3-2 belt_length_km"]
    red = grf(r, Lb / 3.0, Lb / 3.0 / FIX["belt_aspect"], FIX["belt_az"])
    return dict(reduced=red >= np.quantile(red, 1 - p["L3-1 p_reduced"]))

def level4_ore(r, p, F):
    d, basalt = p["L4-1 reach_d_km"], F["basalt"]
    if basalt.any():
        dist = np.where(basalt, ndimage.distance_transform_edt(basalt), ndimage.distance_transform_edt(~basalt)) * DX / 1e3
        zone = (dist <= max(d, 0.5)) & F["reduced"]
    else:
        zone = np.zeros_like(F["reduced"])
    M4, P = p["L4-3 ore_multiplier"], p["L4-2 p_ore"]
    Dg = np.exp(np.linspace(np.log(0.5), np.log(5), 2001)); mean_area = np.mean(np.pi * Dg ** 2 / 4)
    n_ore = r.poisson(P * zone.sum() * (DX / 1e3) ** 2 / mean_area) if zone.any() else 0
    fz = (zone & IN_CIRCLE).sum() / max(zone.sum(), 1)
    ox, oy = weighted_points(r, n_ore, np.where(IN_CIRCLE, M4, 1.0) / (fz * M4 + (1 - fz)), zone)
    ores = []
    for x, y in zip(ox, oy):
        Dk = LU(r, 0.5, 5); th = LU(r, 1, 15); gr = U(r, 1.0, 4.5)
        host = p["L5-2 rho_pandurra"]
        vf = gr / 100 / FIX["cu_in_ccp"] * host / FIX["rho_ccp"]; drho = vf * (FIX["rho_ccp"] - host)
        ix, iy = np.argmin(abs(XC - x)), np.argmin(abs(YC - y))
        ores.append(dict(x=x, y=y, diam_km=Dk, thick_m=th, grade=gr, drho=drho, depth_m=F["contact"][iy, ix],
                         Mt=np.pi * Dk ** 2 / 4 * 1e6 * th * (host + drho) / 1e6, in_circle=bool(IN_CIRCLE[iy, ix])))
    return dict(zone=zone, ores=ores)

def level2_iron(r, p, F):
    """Change 1: iron-oxide bodies (Middleback type) in the basement, top at the unconformity; second object population"""
    n_iron = r.poisson(FIX["iron_ratio"] * p["L2-1 intensity_per_1e4km2"] * AREA_KM2 / 1e4)
    ix_, iy_ = weighted_points(r, n_iron, np.ones((NY, NX)))
    iid = np.zeros((NY, NX), int); irons = []
    for j, (x, y) in enumerate(zip(ix_, iy_), 1):
        L = LU(r, 0.3, 3); rho = U(r, 3.0, 4.5)
        m = ellipse(x, y, L, FIX["iron_aspect"], FIX["iron_az"])
        if not m.any():                                                    # smaller than a cell: keep the nearest cell
            m[np.argmin(abs(YC - y)), np.argmin(abs(XC - x))] = True
        area = np.pi * L ** 2 / 4 / FIX["iron_aspect"]
        fill = min(1.0, area / (m.sum() * (DX / 1e3) ** 2))               # fraction of the marked cells the body fills (mass kept)
        iid[m] = j
        irons.append(dict(obj=j, x=x, y=y, length_km=L, rho=rho, fill=fill, area_km2=area, depth_m=F["base"][np.argmin(abs(YC - y)), np.argmin(abs(XC - x))]))
    return dict(iid=iid, irons=irons)

def level5_basement(r, p, F):
    """Change 1: a lateral basement density field; Change 2: an independent log-normal susceptibility field (both row L5-4 since Change 6)"""
    W = FIX["domain_share"]
    two_scale = lambda: np.sqrt(W) * grf(r, FIX["domain_km"]) + np.sqrt(1 - W) * grf(r, FIX["texture_km"])   # Change 5: domains plus texture, unit variance
    sd = U(r, 0.03, 0.10)                                                 # row L5-4, drawn here so that the earlier stages keep their seeds
    rb = np.clip(FIX["rho_b_mean"] + sd * two_scale(), FIX["rho_b_min"], FIX["rho_b_max"])
    sdk = U(r, 0.5, 1.0)                                                  # row L5-4, decades
    logk = np.clip(np.log10(FIX["k_b_median"]) + sdk * two_scale(), np.log10(FIX["k_b_min"]), np.log10(FIX["k_b_max"]))
    return dict(rho_base=rb, k_base=10.0 ** logk, basement_sd=sd, basement_logk_sd=sdk)

def level5_properties(p, F):
    z = ZC[None, None, :]
    lith = np.full((NY, NX, len(ZC)), 7, np.int8)
    for code, surf in [(1, F["s1"]), (2, F["s2"]), (3, F["s3"]), (4, F["s4"]), (5, F["base"])]:
        lith[(lith == 7) & (z < surf[:, :, None])] = code
    lith[(z >= F["btop"][:, :, None]) & (z < F["base"][:, :, None]) & F["basalt"][:, :, None]] = 6
    rho_u = {1: p["L5-2 rho_limestone"], 2: p["L5-2 rho_quartzite"], 3: p["L5-2 rho_shale"], 4: p["L5-2 rho_shale"],
             5: p["L5-2 rho_pandurra"]}
    rho3 = np.vectorize(lambda c: rho_u.get(c, np.nan))(lith).astype(np.float32)
    k3 = np.where(lith <= 5, p["L5-2 k_cover"], np.nan).astype(np.float32)
    res3 = np.where(lith <= 5, p["L5-2 res_cover"], FIX["res_basement"]).astype(np.float32)
    base3 = lith == 7                                                     # basement takes the Change 1 field, column by column
    rho3 = np.where(base3, F["rho_base"][:, :, None].astype(np.float32), rho3); k3 = np.where(base3, F["k_base"][:, :, None].astype(np.float32), k3)
    for o in F["objs"]:
        m3 = (lith == 6) & (F["bid"][:, :, None] == o["obj"])
        rho3[m3], k3[m3] = o["rho"], o["k"]
    res3[lith == 6] = FIX["res_basalt"]
    for o in F["irons"]:                                                  # iron-oxide bodies: basement cells from the unconformity down 200 m
        m3 = base3 & (F["iid"][:, :, None] == o["obj"]) & (z >= F["base"][:, :, None]) & (z < F["base"][:, :, None] + FIX["iron_thick_m"])
        lith[m3] = 8
        rho3[m3] = rho3[m3] + o["fill"] * (o["rho"] - rho3[m3]); k3[m3] = k3[m3] + o["fill"] * (FIX["k_iron"] - k3[m3])
    return dict(lith=lith, rho=rho3, k=k3, res=res3)

def sh_summary(p, F):
    objs, ores = F["objs"], F["ores"]
    return {"L5-4 basement_sd": F["basement_sd"], "L5-4 basement_logk_sd": F["basement_logk_sd"], **dict(n_basalt=len(objs), basalt_frac=F["basalt"].mean(), reduced_frac=F["reduced"].mean(),
                n_iron=len(F["irons"]), basement_sd_realized=F["rho_base"].std(), basement_logk_sd_realized=np.log10(F["k_base"]).std(),
                zone_km2=F["zone"].sum() * (DX / 1e3) ** 2, n_ore=len(ores), Mt_total=sum(o["Mt"] for o in ores),
                contrast=np.mean([o["rho"] for o in objs]) - p["L5-2 rho_pandurra"] if objs else np.nan)}

BRANCH_SH = dict(name="sediment-hosted Cu, Annex A", citation_table="01_citation_table/wp4_annexA_citation_table_draft.csv",
                 geometry_family="flat-lying cover stack; flow-pile ellipses on the basement surface",
                 mineralization_rule="ore disks in the margin zone: within d of a basalt edge and on a reduced belt",
                 draw=draw, stages=[level1_frame, level2_basalt, level3_redox, level4_ore, level2_iron, level5_basement],   # Change 1 stages last: earlier draws unchanged
                 properties=level5_properties, summary=sh_summary)

def realize_branch(branch, seed, keep_volume=False):
    """one realization of any branch: draw, run the stages in order, attach properties; seed -> numpy default_rng(seed)"""
    r = np.random.default_rng(seed); p = branch["draw"](r); F = {}
    for stage in branch["stages"]:
        F.update(stage(r, p, F))
    out = {"seed": seed, **p, **branch["summary"](p, F)}
    if keep_volume:
        F.update(branch["properties"](p, F))
    maps = {k: v for k, v in F.items() if k not in ("objs", "ores", "basalt", "s4", "basement_sd", "basement_logk_sd")}    # irons (list) stays for plotting
    return out, maps, pd.DataFrame(F["objs"]), pd.DataFrame(F["ores"])

def realize(seed, keep_volume=False):
    return realize_branch(BRANCH_SH, seed, keep_volume)

print(f"mesh: {NX} x {NY} x {len(ZC)} = {MESH.n_cells:,} cells; window {AREA_KM2:,.0f} km2; "
      f"target circles cover {IN_CIRCLE.mean()*100:.1f}% of it; a horst of height A (row L1-3) under each (Change 9)")
print("fixed settings:", {k: round(v, 3) for k, v in FIX.items()})
print(f"grid: origin E {X0:,.0f} m, N {Y0:,.0f} m (GDA94 / MGA zone 53), {NX} x {NY} cells of {DX:.0f} m; "
      f"{len(HZ)} layers: 80 x 25 m to 2,000 m, then {', '.join(f'{v:.0f}' for v in HZ[80:])} m to {sum(HZ):,.0f} m")


# ======== observed values, Step 8 (from the notebook) ========
# ---- observed values: opened here, after the prior; geometry, noise and rule come from Part 0 ------------------------
G_OBS = pd.read_csv(GRAV_FILE, usecols=["SPHERICAL_CAP_BOUGUER_ANOMALY"]).iloc[G_IDX, 0].values / 10.0   # um/s2 to mGal, the Part 0 selection
M_OBS = np.load(CACHE)["mag"][idx]                                        # the readings selected in Part 0, same order
assert len(G_OBS) == len(GXo) and len(M_OBS) == len(MXo)
print(f"gravity: {len(G_OBS)} stations of surveys {sorted(gv.SURVEY_NUMBER.unique())} in the window, {G_OBS.min():.1f} to {G_OBS.max():.1f} mGal, noise sd {np.median(G_SD):.2f} mGal")
print(f"magnetics: {len(M_OBS):,} readings used, {np.nanmin(M_OBS):.0f} to {np.nanmax(M_OBS):.0f} nT; plane-removed residual sd {detrend(MXo, MYo, M_OBS).std():.0f} nT against {RULE['mag_noise_nt']:.0f} nT of declared noise")


# ======== forward operator on the mesh and statistics, Step 9 (from the notebook) ========
# ---- the Part 0 forward operator, instantiated on the sampler mesh -----------------------------------------------------
PADN = 256
forward = make_forward(DX, HZ, PADN, NY, NX)
ZT, ZB = forward.layers; h = FIELD["clearance_m"]

# ---- sampling and synthetic data at the survey points ------------------------------------------------------------------
def sample(field, x, y):
    return RegularGridInterpolator((YC, XC), field, bounds_error=False, fill_value=None)(np.c_[y, x])

def synthetic(seed, rng_noise=True):
    out, maps, objs, ores = realize(seed, keep_volume=True)
    g, t = forward(maps["rho"], maps["k"])
    r = np.random.default_rng(seed + 10_000_000)
    gs = sample(g, GXo, GYo) + (r.normal(0, G_SD) if rng_noise else 0)
    ms = sample(t, MXo, MYo) + (r.normal(0, RULE["mag_noise_nt"], len(MXo)) if rng_noise else 0)
    return out, maps, g, t, gs, ms

OBS_G, GRID_G, ANOM_G = anomaly_stats(TRI_G, GXo, GYo, G_OBS, RULE["T_grav_mgal"])
OBS_M, GRID_M, ANOM_M = anomaly_stats(TRI_M, MXo, MYo, M_OBS, RULE["T_mag_nt"])
print("forward operator ready:", PADN, "x", PADN, "padded grid,", len(ZT), "layers")


