"""Build svoi_core.py from the notebook, so the Sherlock runs use exactly the notebook's sampler and forward operator.

Run from this folder after any change to Part 0 (grid, rule, operator), the sampler (Part A) or Steps 8-9:  python build_core.py
"""
import json
from pathlib import Path

NB = Path(__file__).resolve().parent.parent / "wp4_period_prior_sediment_hosted.ipynb"
cells = [("".join(c["source"])) for c in json.load(open(NB, encoding="utf-8"))["cells"] if c["cell_type"] == "code"]

def one(marker, start=False):
    hit = [s for s in cells if (s.startswith(marker) if start else marker in s)]
    assert len(hit) == 1, (marker, len(hit))
    return hit[0]

parts = [
    ("data and citation table", one('CT = pd.read_csv(PM / "01_citation_table')),
    ("map grid, survey geometry, rule and forward operator, Part 0", one("# ---- Part 0 setup", start=True)),
    ("sampler, Part A", one("# ---- mesh:", start=True)),
    ("observed values, Step 8", one("# ---- observed values", start=True)),
    ("forward operator on the mesh and statistics, Step 9", one("forward = make_forward(").split("# ---- check the FFT operator")[0]),
]
head = '''"""GENERATED by build_core.py from wp4_period_prior_sediment_hosted.ipynb; do not edit by hand.

Import with the SVOI_OD folder as the working directory (paths are relative to it).
"""
'''
body = "\n\n".join(f"# ======== {name} (from the notebook) ========\n{src}" for name, src in parts)
out = Path(__file__).resolve().parent / "svoi_core.py"
out.write_text(head + body + "\n", encoding="utf-8")
print(f"wrote {out.name} from {NB.name} ({len(body.splitlines())} lines)")
